# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

name: pkgdown

on:
  push:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libnlopt-dev libnlopt-cxx-dev libxml2-dev
        
      - uses: r-lib/actions/setup-pandoc@v2
        
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
        
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, any::colorspace, local::.
          needs: website
        
      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = TRUE)
        shell: Rscript {0}
